- name: "Update APT Packages."
  apt:
    update_cache: yes

- name: "Upgrading APT Packages."
  apt:
    upgrade: yes

- name: "Install Utility."
  apt:
    name: [ "software-properties-common", "zip", "unzip", "tar" ]
    state: latest
    update_cache: yes

- name: "Adding Python Repo"
  shell: add-apt-repository ppa:deadsnakes/ppa

- name: "Update APT Packages."
  apt:
    update_cache: yes

- name: "Install Python and Utility."
  apt:
    name: ["python3.8"]
    state: latest
    update_cache: yes

- name: install node
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash - && sudo apt-get install -y nodejs


- name: "Installing pm2"
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
